services:
  web:
    build: .
    ports:
      - "8083:8000"
    volumes:
      - ./app:/app/app
    env_file: .env
    restart: unless-stopped

#   ollama:
#     image: ollama/ollama:latest
#     volumes:
#       - ollama_data:/root/.ollama
#     ports:
#       - "11434:11434"
#     deploy:
#       resources:
#         reservations:
#           devices:
#             - driver: nvidia
#               count: all
#               capabilities: [gpu]

# volumes:
#   ollama_data:
