name: Build and Push

on:
  workflow_dispatch:

  push:
    branches: [main]

jobs:
  build-and-push:
    runs-on: docker
    steps:
      - uses: actions/checkout@v4

      - uses: https://git.paynepride.com/nic/homelab-mono/devops/ci/forgejo-actions/docker-build-push@main
        with:
          repoflow_workspace: foo
          repoflow_password: ${{ secrets.REPOFLOW_PASSWORD_RW }}
          repoflow_user: ${{ secrets.REPOFLOW_USER_RW }}
